# -*- coding: utf-8 -*-
"""arxivmodelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/129Y6mK9BiV-Ef3_FmMcXUXqFURJq2Faj
"""

!pip install langchain_huggingface
!pip install langchain_community
!pip install arxiv
!pip install sentence-transformers
!pip install faiss-cpu
#!pip install numpy==1.26.4

from langchain_huggingface import HuggingFaceEmbeddings
EMB = HuggingFaceEmbeddings(
    model_name='sentence-transformers/all-MiniLM-L6-v2',
    model_kwargs=
    {
        'device': 'cuda'
    }
)

!CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install llama-cpp-python==0.2.77 -U --force-reinstall --no-cache-dir --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121

from langchain_core.prompts import PromptTemplate
from langchain_community.llms import LlamaCpp
from langchain_community.chat_models import ChatLlamaCpp
from langchain_core.callbacks import CallbackManager, StreamingStdOutCallbackHandler
from arxiv import Search
import pandas as pd
import numpy as np
import os
import json
import warnings
import logging
import time
import psutil

warnings.filterwarnings("ignore")

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

from huggingface_hub import hf_hub_download

# Llama-2-7B-Chat
model_name = "llama-2-7b-chat.Q4_K_M.gguf"
model_repo_id = "TheBloke/Llama-2-7B-Chat-GGUF"
model_path_folder = "./models"


os.makedirs(model_path_folder, exist_ok=True)

# Download
llm_model_path = hf_hub_download(
    repo_id=model_repo_id,
    filename=model_name,
    local_dir=model_path_folder,
    local_dir_use_symlinks=False
)

print(f"New model downloaded to: {llm_model_path}")

class QAbot():
    def __init__(self, prompt, Embeddings):
        self.EMBEDDINGS = Embeddings
        self.custom_prompt_template = prompt
        self.callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])
        self.llm = self.load_llm()
        self.refer = ""


    def set_custom_prompt(self, context: str, question: str):
        """
        Create a prompt using the provided context and question.
        """
        prompt_template = PromptTemplate(template=self.custom_prompt_template, input_variables=['context', 'question'])
        prompt = prompt_template.format(context=context, question=question)
        logger.info("The prompt was created.")
        return prompt


    def fetch_arxiv_data(self, query):
        search = Search(
            query=query,
            max_results=1,
        )
        papers = list(search.results())
        sorted_papers = sorted(papers, key=lambda paper: paper.published, reverse=True)  # Sort by publication date
        logger.info("The data retrieved was created.")
        return sorted_papers


    def load_llm(self):
        """
        Loading the LLM using Llama Cpp.
        """
        llm = LlamaCpp(
            model_path=llm_model_path,
            callback_manager = self.callback_manager,
            n_ctx=3072,
            max_tokens = 4096, #idk if this is ok
            n_gpu_layers=-1,
            verbose=False,
            flash_attn=True,
            chat_format = None
        )
        logger.info("LLM model loaded.")
        print("LLM Model Loaded")
        return llm


    def qa_bot(self, question: str):
        """
        Manually perform the search, create the prompt, and get the response from the LLM.
        """
        arxiv_data = self.fetch_arxiv_data(question)
        context = ""
        for papers in arxiv_data:
            context += "**" + papers.title + "**\n"
            context += papers.summary + "\n\n"

        prompt = self.set_custom_prompt(context, question)
        print(f"Prompt\n{prompt}\n-----------------------------------")
        return self.llm.invoke(prompt)

    def get_reference(self):
        return self.refer

prompt = """
    based on the following metadata from arxiv.org
    {context}

    Summarize the research paper into the following four chunks, providing a brief summary of the main ideas and key points for each:
    ## 1. Introduction
    -
    ## 2. Discussion
    -
    ## 3. Conclusion
    -
    ## 4. Further Reading
    -
"""

qa_instance = QAbot(prompt, EMB)

def main():
    start_time = time.time()
    ans = []
    question = input("Enter your question below\n")

    final = ""
    l = []
    for chunk in qa_instance.qa_bot(question):
        l.append(time.time())
        final += str(chunk)

    print(final)
    _o = qa_instance.get_reference()
    ans.append([question, final, _o])

if __name__ == "__main__":
    main()